### ISSUE TITLE
Link on a setup page doesn't open

### ISSUE THREAD

**Issue by Onexx** [artie-shevchenko/pr-review-your-turn#30]
Nothing happens when I click on a link on this page. Tried on Ubuntu, btw
![image](https://github.com/artie-shevchenko/pr-review-your-turn/assets/38791099/d3678f23-271a-4e98-a912-7979f0ca2acd)

**Comment by artie-shevchenko** [comment]
@Onexx "Generate a GitHub token" link doesn't open?

**Comment by Onexx** [comment]
Yes, nothing happened when I clicked on it. I had to copy and paste the link

**Comment by artie-shevchenko** [comment]
@Onexx could you try it again please?

**Comment by Onexx** [comment]
@artie-shevchenko It woks now, thanks! (not in Chrome Web Store yet?)
