### ISSUE TITLE
The "hours you ignored it" doesn't seem to update.

### ISSUE THREAD

**Issue by Onexx** [artie-shevchenko/pr-review-your-turn#32]
![image](https://github.com/artie-shevchenko/pr-review-your-turn/assets/38791099/738a30fc-642e-490b-94eb-36f928c62e72)
![image](https://github.com/artie-shevchenko/pr-review-your-turn/assets/38791099/cc411a2a-41c8-4441-b99b-558ad4368499)

**Comment by artie-shevchenko** [comment]
@Onexx maybe you just reinstalled the plugin and that's why? Is the problem still there?

**Comment by artie-shevchenko** [comment]
@Onexx what do you mean by "time in GitHub"?

**Comment by Onexx** [comment]
@artie-shevchenko Wait, time in plugin shoudn't copy time in github? I'm about second screenshot in this bug
