### ISSUE TITLE
Support other "Your turn" use cases

### ISSUE THREAD

**Issue by artie-shevchenko** [artie-shevchenko/pr-review-your-turn#4]
Currently the only thing extension notifies you of is if somebody requests a review from you. There are more scenarios that require your attention:

* [p2] Somebody mentions you, but you didn't reply in that thread.
* Somebody submits a "Changes requested" review on your PR.
* [Depends on the workflow - should be settings-controlled] Somebody submits a "Comment" review on your PR.

**Comment by Onexx** [comment]
Maybe I shouldn't see that it's my turn if MR is marked as draft?

**Comment by artie-shevchenko** [comment]
replaced with #26 and #27.
